# Generated by Django 4.2.2 on 2023-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='resposta_chatgpt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='texto_usuario',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='data_ida',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='data_volta',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
