# Generated by Django 4.2.2 on 2023-08-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_roteiro_resposta_chatgpt_roteiro_texto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='custo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='partida',
            field=models.CharField(choices=[('Recife', 'Recife'), ('Porto de Galinhas', 'Porto de Galinhas'), ('São Paulo', 'São Paulo'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Salvador', 'Salvador'), ('Fortaleza', 'Fortaleza')], default='Partida', max_length=100),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='data_ida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='data_volta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='destino',
            field=models.CharField(choices=[('Recife', 'Recife'), ('Porto de Galinhas', 'Porto de Galinhas'), ('São Paulo', 'São Paulo'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Salvador', 'Salvador'), ('Fortaleza', 'Fortaleza')], default='Destino', max_length=100),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='resposta_chatgpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='texto_usuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
